# Generated by Django 4.0.2 on 2023-05-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_created_by_field_to_address_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stripe_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
